version: 1.0.{build}
branches:
  only:
  - dev
image: Visual Studio 2017
clone_folder: c:\openpose-python

environment:
  APPVEYOR_RDP_PASSWORD: Abc123

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - cmd: set PATH=C:\Python36-x64;%PATH%
  - cmd: set PATH=C:\Python36-x64\Scripts;%PATH%
  - cmd: echo Installing wheel setuptools
  - cmd: pip3.6 install wheel setuptools
  - cmd: echo Installing CUDA toolkit
  - cmd: appveyor DownloadFile https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_win10 -FileName cuda.exe
  - cmd: cuda.exe -s nvcc_10.0 nvprune_10.0 cublas_dev_10.0 cufft_dev_10.0 curand_dev_10.0 cusolver_dev_10.0 cusparse_dev_10.0 nvgraph_dev_10.0 npp_dev_10.0 nvrtc_dev_10.0 nvml_dev_10.0
  - cmd: set PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;%PATH%
  - cmd: echo Installing cudnn
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/45pboe5e5dhz8gm/cudnn.rar?dl=1
  - cmd: 7z.exe x cudnn.rar 
  - cmd: copy "cudnn\bin\*.*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin"
  - cmd: copy "cudnn\lib\x64\*.*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64"
  - cmd: copy "cudnn\include\*.*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include"

build_script:
  - cmd: cd ..
  - cmd: git clone https://github.com/CMU-Perceptual-Computing-Lab/openpose.git
  - cmd: cd openpose
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DBUILD_PYTHON=ON -DBUILD_EXAMPLES=OFF -G "Visual Studio 15 2017 Win64" ..
  - cmd: cmake --build . --config "Release"
  - cmd: copy "bin\*.dll" "c:\openpose-python\pyopenpose"
  - cmd: copy "python\openpose\Release\*.pyd" "c:\openpose-python\pyopenpose"
  - cmd: copy "x64\Release\*.dll" "c:\openpose-python\pyopenpose"
  - cmd: cd "c:\openpose-python\"
  - cmd: python setup.py bdist_wheel
  - cmd: cd dist
  - cmd: rename "python_openpose-1.5.1-py3-none-any.whl" "python_openpose-1.5.1-py3-none-win_amd64.whl"
  - cmd: copy "*.whl" "c:\"
artifacts:
  - path: python_openpose-1.5.1-py3-none-win_amd64.whl
    name: python_openpose-1.5.1