version: {build}
branches:
  only:
  - dev
image: Visual Studio 2017
clone_folder: c:\openpose-python

before_build:
  - cmd: echo Installing CUDA toolkit
  - cmd: appveyor DownloadFile https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_win10 -FileName cuda.exe
  - cmd: cuda.exe -s nvcc_10.0 nvprune_10.0 cublas_dev_10.0 cufft_dev_10.0 curand_dev_10.0 cusolver_dev_10.0 cusparse_dev_10.0 nvgraph_dev_10.0 npp_dev_10.0 nvrtc_dev_10.0 nvml_dev_10.0 visual_studio_integration_10.0
  - cmd: set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;%PATH%
  - cmd: if NOT EXIST "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudart64_90.dll" ( 
echo "Failed to install CUDA"
exit /B 1
)
  - cmd: echo Installing cudnn
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/45pboe5e5dhz8gm/cudnn.rar?dl=1
  - cmd: 7z.exe x cudnn.rar 
  - cmd: copy cudnn\cuda\bin\*.* "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin"
  - cmd: copy cudnn\cuda\lib\x64\*.* "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64"
  - cmd: copy cudnn\cuda\include\*.* "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include"

build:
  verbosity: minimal